apiVersion: v1
kind: Service
metadata:
  name: supertuxkart-service
  labels:
    app: supertuxkart
spec:
  type: NodePort
  selector:
    app: supertuxkart
  ports:
    - name: tcp-2757
      protocol: TCP
      port: 2757
      targetPort: 2757
      nodePort: 30007
    - name: udp-2757
      protocol: UDP
      port: 2757
      targetPort: 2757
      nodePort: 30017
    - name: tcp-2759
      protocol: TCP
      port: 2759
      targetPort: 2759
      nodePort: 30009
    - name: udp-2759
      protocol: UDP
      port: 2759
      targetPort: 2759
      nodePort: 30019

